# Generated by Django 5.0.2 on 2024-02-07 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testform', '0002_session_form'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='form',
            table='form',
        ),
        migrations.AlterModelTable(
            name='session',
            table='session',
        ),
        migrations.AlterModelTable(
            name='teacher',
            table='teacher',
        ),
    ]
