# Generated by Django 5.0.2 on 2024-02-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testform', '0003_alter_form_table_alter_session_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='end',
            field=models.DateTimeField(null=True),
        ),
    ]
