# Generated by Django 5.0.2 on 2024-02-08 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testform', '0004_alter_form_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='session',
        ),
        migrations.AddField(
            model_name='session',
            name='form',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='testform.form'),
            preserve_default=False,
        ),
    ]
