# Generated by Django 5.0.2 on 2024-02-09 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testform', '0007_alter_session_teacher_delete_teacher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Form',
            new_name='Review',
        ),
        migrations.AlterField(
            model_name='session',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='review',
            table='review',
        ),
    ]
